{% set name = "cyclopts" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cyclopts-{{ version }}.tar.gz
  sha256: 3576ffcaa1f40c53aa77a228de8f7e9e34fd48ff46f18046af1feccbbc66970b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning >=1.0.1
    - pip
  run:
    - python >={{ python_min }}
    - typing_extensions >=4.8.0
    - attrs >=23.1.0
    - rich >=13.6.0
    - rich-rst >=1.3.1,<2.0.0
    - docstring_parser >=0.15
    - importlib-metadata >=4.4

test:
  imports:
    - cyclopts
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/BrianPugh/cyclopts
  doc_url: https://cyclopts.readthedocs.io/
  summary: Intuitive, easy CLIs based on python type hints.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
