{% set name = "cyclopts" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cyclopts-{{ version }}.tar.gz
  sha256: 1c942e96fd0b238d8c2e17104ab78051cc750d401341c0272df1050d15f37a59

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning >=1.0.1
    - pip
  run:
    - python >=3.8,<4.0
    - typing-extensions >=4.8.0
    - attrs >=23.1.0
    - rich >=13.6.0
    - rich-rst >=1.2.0,<2.0.0
    - docstring_parser >=0.15.0,<0.16.0
    - importlib-metadata >=4.4

test:
  imports:
    - cyclopts
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/BrianPugh/cyclopts
  doc_url: https://cyclopts.readthedocs.io/
  summary: Intuitive, easy CLIs based on python type hints.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
