schema_version: 1

context:
  name: cyclopts
  version: "4.0.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/cyclopts-${{ version }}.tar.gz
  sha256: 0dae712085e91d32cc099ea3d78f305b0100a3998b1dec693be9feb0b1be101f

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=${{ python_min }}
    - attrs >=23.1.0
    - rich >=13.6.0
    - docstring_parser >=0.15,<4.0
    - rich-rst >=1.3.1,<2.0.0
    - typing_extensions >=4.8.0
    - tomli >=2.0.0

tests:
  - python:
      imports:
        - cyclopts
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Intuitive, easy CLIs based on python type hints.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/BrianPugh/cyclopts
  documentation: https://cyclopts.readthedocs.io/

extra:
  recipe-maintainers:
    - thewchan
